<a href="https://colab.research.google.com/github/lissettzuniga/data-science-course/blob/main/notebooks/estilizacion_de_tablas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Visualization: Estilizando tablas con python**

## **Extracción y preparación de los datos**

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

In [ ]:
ventas = pd.read_csv('https://gist.githubusercontent.com/ahcamachod/d2efadda3f3833d65da750c64705ac42/raw/80aef6f3bad210d34b67ed85565f039a30e2d9e0/ventas.csv',sep='#')

In [ ]:
ventas.head()

,fecha_pedido,fecha_envio,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,precio_base,precio_unit_sin_descuento,descuento,precio_unit_venta,cantidad,ventas,ganancia
0,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,35.88,42.24,0.100,38.02,2,76.04,4.28

In [ ]:
ventas = ventas[['fecha_pedido','modo_envio','nombre_cliente','segmento_cliente','ciudad','provincia','region','departamento',
                'tipo_producto','ventas','cantidad','ganancia']]

In [ ]:
ventas.head(2)

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29

In [ ]:
ventas.shape

(8940, 12)

In [ ]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.3+ KB

In [ ]:
ventas['fecha_pedido'] = pd.to_datetime(ventas['fecha_pedido'],format='%Y-%m-%d')

In [ ]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.3+ KB

## Misión 1: Equipo de Ventas

Necesitamos construir una visualización para indicar los **10 principales clientes por total de ventas**.

Con ello, el equipo de ventas puede pensar en estrategias para mantener a estos clientes comprando en nuestra tienda.

fecha_pedido: fecha en que el cliente realizó el pedido del producto.

modo_envio: modo de envío del producto especificado por el cliente.

nombre_cliente: nombre del cliente.

segmento_cliente: el segmento al que pertenece el cliente, pudiendo ser B2B o B2C.

ciudad: ciudad de destino del pedido.

provincia: provincia de destino del pedido.

region: región del estado de destino del pedido.

departamento: departamento del producto encargado.

tipo_producto: categoría del producto encargado.

ventas: valor ganado de la venta del producto.

cantidad: cantidad pedida del producto encargado.

ganancia: valor de ganancia/pérdida para la empresa considerando los gastos del producto.

In [ ]:
clientes = ventas.groupby(['nombre_cliente'])['ventas'].sum().nlargest(10).copy().reset_index()

In [ ]:
clientes

      nombre_cliente    ventas
0    Víctor Carrasco  73370.61
1        Brisa Rojas  68868.11
2       Mateo Vargas  62749.75
3      Vicente Rojas  59544.11
4        Laura Rojas  51398.87
5         Lucía Díaz  48178.99
6   Cristina Barrios  47610.80
7  Alejandro Sánchez  43769.25
8      Pamela Huerta  42354.19
9     Carlos Sánchez  41238.81

In [ ]:
clientes.columns = ['Clientes','ventas']
clientes['Ranking'] = clientes.index + 1
clientes.set_index('Ranking',inplace=True)

In [ ]:
clientes

                  Clientes    ventas
Ranking
1          Víctor Carrasco  73370.61
2              Brisa Rojas  68868.11
3             Mateo Vargas  62749.75
4            Vicente Rojas  59544.11
5              Laura Rojas  51398.87
6               Lucía Díaz  48178.99
7         Cristina Barrios  47610.80
8        Alejandro Sánchez  43769.25
9            Pamela Huerta  42354.19
10          Carlos Sánchez  41238.81

In [ ]:
estilo = clientes.style
estilo

In [ ]:
estilo.format({'ventas':'{:,.2f}'})
estilo

In [ ]:
import pandas as pd

# DataFrame con películas bien valoradas
datos = {
    'Género': ['Drama', 'Comedia', 'Acción', 'Ciencia Ficción', 'Terror'],
    'Nota Media': [4.5, 4.3, 4.2, 4.1, 3.8],
    'Cantidad de Evaluaciones': [1500, 1200, 1000, 800, 600]
}

df_peliculas = pd.DataFrame(datos)

# Añade un ranking de popularidad basado en el número de evaluaciones
df_peliculas['Ranking'] = df_peliculas['Cantidad de Evaluaciones'].rank(method='dense', ascending=False).astype(int)

# Define la columna 'Ranking' como índice del DataFrame
df_peliculas.set_index('Ranking', inplace=True)

# Objeto style
s_pelicula = df_peliculas.style

# Crear un archivo HTML
s_pelicula.to_html('estilo_html.html', index=False)

# Crear un archivo Excel
s_pelicula.to_excel('estilo_xlsx.xlsx', engine='openpyxl')

# Crear un archivo LaTeX
with open('estilo_latex.tex', 'w') as f:
    f.write(s_pelicula.to_latex())

# Misión 2: Equipo Comercial

Necesitamos construir una visualización que permita asociar el **total de ganancias en ventas y el total de lucros por tipo de producto**.

Ello permitirá que el equipo comercial pueda enfocarse en estrategias para apalancar los ingresos que se reciben con cada tipo de producto vendido en la tienda.

In [ ]:
ganancias_ventas = ventas.groupby(['tipo_producto'])[['ventas','ganancia']].sum()

In [ ]:
ganancias_ventas.index.name = 'tipo de producto'
ganancias_ventas

                                 ventas  ganancia
tipo de producto
Brotes                          8811.32   1381.42
Decoración de jardín           82680.08   9939.43
Equipos de limpieza           542304.58   8724.39
Fertilizantes                  53144.74  11254.88
Fontanería                    373223.88  -5622.34
Herramientas                  995158.41  41020.34
Herramientas automotrices     502109.29  63330.22
Herramientas de jardinería    648879.72  53202.88
Iluminación                   275229.53  20264.54
Macetas                       696044.18  33941.85
Materiales de paisajismo      150552.49  -1912.37
Materiales de revestimiento   629656.36 -28869.01
Muebles de exterior           328932.27  26784.59
Neumáticos                   1022428.97  67460.05
Pesticidas                    244956.04  53343.89
Piezas de repuesto            486907.94  91148.67
Semillas                       39979.75   8865.09

In [ ]:
estilo_producto = ganancias_ventas.style
estilo_producto

In [ ]:
estilo_producto.format('USD {:,.2f}')

In [ ]:
estilo_producto = estilo_producto.format('USD {:,.2f}').highlight_max(color='lightgreen').highlight_min(color='red')

In [ ]:
estilo_producto

In [ ]:
estilo_producto.background_gradient(cmap='Reds')

In [ ]:
encabezado = {
    'selector': 'th',
    'props': 'font-weight:bold; font-family:Arial; text-align:center; text-transform:capitalize'
}

estilo_producto.set_table_styles([encabezado], overwrite=False)

# Misión 3: Equipo de Logística

Necesitamos construir una visualización que nos permita entender la **distribución de pedidos por región de Brasil**.

Así, el equipo de logística va a saber dónde hay más oportunidad de enfocar los esfuerzos de material y mano de obra.

In [ ]:
region = pd.DataFrame(ventas['region'].value_counts())
region.columns = ['N° Pedidos']
region.index.name = 'Region'
region

              N° Pedidos
Region
Buenos Aires        2822
Litoral             1924
Norte               1555
Central             1276
Cuyo                 915
Patagónica           448

In [ ]:
import numpy as np

In [ ]:
porcentaje = region['N° Pedidos'].to_numpy()
porcentaje = 100 * porcentaje / porcentaje.sum()
porcentaje

array([31.56599553, 21.5212528 , 17.39373602, 14.27293065, 10.23489933,
        5.01118568])

In [ ]:
region['Porcentaje de pedidos'] = porcentaje
region

              N° Pedidos  Porcentaje de pedidos
Region
Buenos Aires        2822              31.565996
Litoral             1924              21.521253
Norte               1555              17.393736
Central             1276              14.272931
Cuyo                 915              10.234899
Patagónica           448               5.011186

####**Características visuales que pueden ser alteradas en código mediante la definición de propiedades**
background-color: define el color de fondo de la tabla o de una celda específica;

color: define el color del texto de la tabla o de una celda específica;

border: define el borde de la tabla o de una celda específica, incluyendo el ancho, estilo y color del borde;

border-collapse: define si los bordes de las celdas de la tabla deben estar combinados o separados;

text-align: define la alineación horizontal del texto en una celda específica;

vertical-align: define la alineación vertical del contenido de una celda específica;

font-size: define el tamaño de la fuente del texto de la tabla o de una celda específica;

font-weight: define el grosor de la fuente del texto de la tabla o de una celda específica;

padding: define el espacio interno entre el contenido y el borde de una celda específica.

In [ ]:
region_estilo = region.style
region_estilo

In [ ]:
encabezado = {
    'selector': 'th',
    'props': 'font-weight:bold; font-family:Arial; text-align:right; background-color:white'
}

celdas = {
    'selector': 'td',
    'props': 'background-color:white'
}

region_estilo.set_table_styles([encabezado,celdas])

In [ ]:
region_estilo.format({'Porcentaje de pedidos':'{:.2f}%'})\
                     .bar(subset='Porcentaje de pedidos',vmin=0,vmax=100,color='#9cd3bb')

# Misión 4: Equipo de Logística

Nuevamente el equipo de logística desea replantear su estructura y organización de provisionamiento de productos e, para ello, se pensó en una visualización que permita identificar el estándar de la **cantidad de productos solicitados por mes por departamento**.

In [ ]:
meses = ventas.copy()
meses = meses.sort_values('fecha_pedido')
#meses['mes'] = meses['fecha_pedido'].dt.month
meses

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
7171,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44
651,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32
650,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13
649,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26
1576,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31
...,...,...,...,...,...,...,...,...,...,...,...,...
796,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63
795,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69
794,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60
1151,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68
1152,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00

In [ ]:
meses['mes'] = meses['fecha_pedido'].dt.strftime('%Y-%b')
meses = meses.reset_index(drop=True)

In [ ]:
meses

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia,mes
0,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44,2016-Jan
1,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32,2016-Jan
2,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13,2016-Jan
3,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26,2016-Jan
4,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31,2016-Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63,2019-Dec
8936,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69,2019-Dec
8937,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60,2019-Dec
8938,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68,2019-Dec
8939,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00,2019-Dec

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
ventas_mensuales = meses.pivot_table(index=meses.departamento,columns='mes',values='cantidad',aggfunc='sum',sort=False)
ventas_mensuales

mes,2016-Jan,2016-Feb,2016-Mar,2016-Apr,2016-May,2016-Jun,2016-Jul,2016-Aug,2016-Sep,2016-Oct,2016-Nov,2016-Dec,2017-Jan,2017-Feb,2017-Mar,2017-Apr,2017-May,2017-Jun,2017-Jul,2017-Aug,2017-Sep,2017-Oct,2017-Nov,2017-Dec,2018-Jan,2018-Feb,2018-Mar,2018-Apr,2018-May,2018-Jun,2018-Jul,2018-Aug,2018-Sep,2018-Oct,2018-Nov,2018-Dec,2019-Jan,2019-Feb,2019-Mar,2019-Apr,2019-May,2019-Jun,2019-Jul,2019-Aug,2019-Sep,2019-Oct,2019-Nov,2019-Dec
departamento,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Jardinería y paisajismo,161,87,277,323,270,273,348,339,549,276,716,525,97,131,278,271,269,321,268,322,663,260,746,628,190,177,260,338,463,473,413,380,757,402,727,770,361,205,458,415,542,490,423,561,929,617,946,989
Automotriz,45,20,46,107,81,83,91,95,154,85,236,154,55,44,74,111,94,59,88,117,180,100,179,235,59,49,112,72,124,118,117,123,181,103,253,189,109,63,167,87,150,170,168,136,280,205,331,252
Materiales de construcción,60,23,102,69,91,114,104,101,182,94,213,269,93,38,100,85,76,120,128,106,194,129,259,258,91,67,127,128,171,117,132,113,227,171,308,294,83,67,107,131,172,151,162,132,282,213,312,395

In [ ]:
estilo_mensual = ventas_mensuales.style
estilo_mensual

In [ ]:
estilo_mensual.set_sticky(axis='index')

In [ ]:
columnas = {
    'selector': '.col_heading',
    'props': 'font-weight:normal; font-family:Arial'
}

tabla = {
    'selector': 'td,th',
    'props': 'text-align:left'
}

indices = {
    'selector': '.index_name',
    'props': 'font-weight:bold; font-family:Arial; text-align:right'
}

estilo_mensual.set_table_styles([columnas,tabla,indices],overwrite=False)

# Misión 5: Informe de Desempeño

El informe de desempeño es un documento muy importante para la empresa. En este, todos los que trabajan en la tienda pueden entender cómo está la empresa. Debido a ello, las tablas bien construídas son esenciales para mostrar los datos de la mejor forma.

Por lo tanto, necesitamos construir una visualización que permita entender la **relación entre tipos de clientes y modo de envío de productos de acuerdo con las ventas**. De esta forma, será posible destacar en el informe cuál es el modo de envío y cuáles son los que más generaron lucro en las ventas.

In [ ]:
df_cliente = ventas.pivot_table(index='segmento_cliente',columns='modo_envio',values='ventas',aggfunc='sum')
df_cliente

modo_envio,Económica,Entrega en 24 horas,Entrega estándar,Envío rápido
segmento_cliente,,,,
B2B,718461.22,217465.60,1884738.56,602049.40
B2C,729174.73,182531.47,2248283.69,498294.88

In [ ]:
df_cliente['Total'] = df_cliente.sum(axis=1)
df_cliente.loc['Total'] = df_cliente.sum()
df_cliente

modo_envio,Económica,Entrega en 24 horas,Entrega estándar,Envío rápido,Total
segmento_cliente,,,,,
B2B,718461.22,217465.60,1884738.56,602049.40,6845429.56
B2C,729174.73,182531.47,2248283.69,498294.88,7316569.54
Total,1447635.95,399997.07,4133022.25,1100344.28,14161999.10

In [ ]:
compra_cliente =df_cliente.style.format('{:,.2f}')
compra_cliente

In [ ]:
tabla = {
    'selector': 'td,th:not(.index_name)',
    'props': 'font-weight:normal; font-family:Arial; text-align:center; background-color:white'
}

indice = {
    'selector': '.index_name',
    'props': 'font-weight:normal; font-style:italic; text-align:right; color:#696969'
}

compra_cliente.set_table_styles([tabla, indice])

In [ ]:
compra_cliente.set_table_styles({
    'Total': [
        {
            'selector': 'th',
            'props': 'border-top: 2px solid #181818'
        },
        {
            'selector': 'td',
            'props': 'border-top: 2px solid #181818'
        }
    ],
    'B2B': [
        {
            'selector': 'th',
            'props': 'border-top: 2px solid #181818'
        },
        {
            'selector': 'td',
            'props': 'border-top: 2px solid #181818'
        }
    ]
},overwrite=False,axis=1)

In [ ]:
compra_cliente.set_table_styles({
    'Total': [{
        'selector': '.true',
        'props': 'background-color: #D8D8D8'
    }]
}, overwrite=False, axis=0)

colores_columna = pd.DataFrame(['false', 'true', 'false'],index=df_cliente['Total'].index,columns=['Total'])

compra_cliente.set_td_classes(colores_columna)

In [ ]:
import pandas as pd
df = pd.read_csv('https://gist.githubusercontent.com/ahcamachod/52da15c2bbb31e4270b5c267dd051473/raw/62c366878ebd4be2ec899836413c8d1f3e116c01/tienda_libros.csv')

In [ ]:
# Crear un DataFrame alternativo para tener un nombre de columna coherente con la visualización
df_alteracion = df.rename(columns={'pais': 'Costo por país ($)'})

# Agrupar los datos por tipo de cliente, con la categoría de productos y los países a los que estos clientes importan el producto
df_clientes = df_alteracion.pivot_table(index=['tipo_cliente', 'categoria'], columns = 'Costo por país ($)', values = 'costo_producto', aggfunc = 'sum')

# Renombrar el encabezado para nombres más coherentes
df_clientes.rename_axis(index={'tipo_cliente': 'Tipo cliente', 'categoria': 'Categoría producto'}, inplace = True)

# Agregar una columna que muestre la suma de los costos por tipo de cliente y categoría de producto
df_clientes['Total ($)'] = df_clientes.sum(axis=1)

## Crear la visualización
s_clientes = df_clientes.style.format('{:,.2f}')

# Crear los estilos base para la tabla, desde la estandarización de las fuentes, fondo blanco y alineación del encabezado en la parte superior
tabla = {
    'selector': 'td, th',
    'props': 'font-weight: normal; font-family: Arial; text-align: right; background-color: white;'
}
# Alinear verticalmente el encabezado en la parte superior permite al observador identificar dónde comienza la jerarquización de los grupos B2B y B2C
encabezado = {
    'selector': 'th',
    'props': 'vertical-align: top'
}
s_clientes.set_table_styles([tabla, encabezado])

# Agregar línea de separación en el encabezado superior
# Resaltar las categorías que generaron más costo con la aplicación de negrita en las fuentes
s_clientes.set_table_styles({
    ('B2B', 'BlueRay'): [{'selector': 'th', 'props': 'border-top: 1px solid #181818'},
              {'selector': 'td', 'props': 'border-top: 1px solid #181818'}],
    ('B2B', 'Libro'): [{'selector': 'th', 'props': 'font-weight: bold'}],
    ('B2C', 'Libro'): [{'selector': 'th', 'props': 'font-weight: bold'}],
}, overwrite=False, axis=1)

# Resaltar los elementos en cada tipo de cliente que generaron más costos con una selección
s_clientes.set_table_styles({
    'Total ($)': [{
        'selector': '.true',
        'props': 'font-weight: bold'
    }]
},overwrite=False,axis=0)

colores_columna = pd.DataFrame(['false','false','false','true','false','false','false','true'],index= df_clientes['Total ($)'].index,
                            columns = ['Total ($)'])
# Visualización final
s_clientes.set_td_classes(colores_columna)